project_id = "gmcfdipxjsbkxdfrjpok"

[functions.encrypt-totp-secret]
verify_jwt = true

[functions.manage-subscription]
verify_jwt = true

[functions.fetch-ndf]
verify_jwt = false

[functions.xx-network-health]
verify_jwt = false